name: Audit dependencies

permissions:
  issues: write
  checks: write

on:
  schedule:
    # Run weekly Monday morning
    - cron: "49 4 * * 1"

  workflow_dispatch:

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # 5.0.1

      - name: Audit dependencies
        uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # 2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
